### PR TITLE
NEW: Make NXConverter a context manager which raises human-friendly errors

### PR DESCRIPTION
**Pull request by carterbox**
The purpose of this PR is to refactor the NXConverter class so that required data is handled differently. Previously, many parameters had a default value of `None` even if they are required according to the NXcxi_ptycho format requires it to be specified. Now, required data is required by the functions which write it to the file and if the NXConverter is used as a context manager, then the TypeErrors which are raised by missing arguments are chained with a message which tells the user that they may be omitting required arguments.

An alternate approach could be to use function decorators instead of a context manager to annotate missing arguments, but this approach was suggested in the informal meeting.

- [x] Convert NXConverter to a context manager
- [x] Catch and reraise attribute error if required parameters are missing

Demo how errors are handled with the following code bit:
```python
from creator.nx_creator_ptycho import NXCreator

with NXCreator('test.nx') as creator:
    creator.create_entry_group()
    creator.create_beam_group()
```

### CODE REVIEW

**Review by leofang — COMMENTED** [review]
Thanks, @carterbox! [Your changes](https://github.com/lightsources/NX-cxi-ptycho/compare/5bccca53..42ae664) look reasonable to me. My only question is if `test_context.py` would actually run with `unittest` or `pytest`, or it's only for the demo purpose?

**Comment by JulReinhardt** [comment]
Looks all good to me, @carterbox . I am happy to merge this to main. Then refactor branch PR becomes obsolete, as this PR was branched from "refactor". We can work on more changes branching from main then. Any objections?

**Comment by carterbox** [comment]
@leofang, it's just a demo. There are no assert statements, so it wouldn't function as a test.

@JulReinhardt, I wasn't sure what the objectives of #7, so I was just going to wait until #7 was merged and then rebase this PR on top of the master branch. Either way is fine with me.

**Comment by carterbox** [comment]
Could also just merge this branch into your branch.

**Review by JulReinhardt — COMMENTED** [review]
merge into refactor

**Pull request merged**
